### ISSUE TITLE
Question: how the static metric is faster?

### ISSUE THREAD

**Issue by augustocdias** [tikv/rust-prometheus#299]
I was trying to understand how the static metric is faster if we have to use the `MetricVec` anyways to register them...

In [this example](https://github.com/tikv/rust-prometheus/blob/master/static-metric/examples/with_lazy_static.rs) you provided it will still use the `CounterVec`.

What is the real benefit of using it in the end?

**Comment by breeswish** [comment]
Hi, static metric is faster due to avoiding the cost of calculating the label hash when specifying via label, as well as some initial cost when label is initially created.

In the example, `HTTP_COUNTER` is the static metric (for the metric vector), which has pre-built labels as fields. Specifying labels for static metrics is only a field access, instead of heavy calculation.

To be most efficient, it is also recommended to use local metrics. You can even have local static metric, which should provide the ultimate performance. However they are even more complicated so that I suggest you to instrument your application first to see how much time it really takes in the metrics.
