### ISSUE TITLE
replace the abandoned spin dependency

### ISSUE THREAD

**Issue by bbigras** [tikv/rust-prometheus#305]
[cargo-audit](https://github.com/RustSec/cargo-audit) complains about this dependency.

> The author of the spin crate does not have time or interest to maintain it.

>Consider the following alternatives (both of which support no_std):
> - conquer-once
> - lock_api (a subproject of parking_lot)

https://rustsec.org/advisories/RUSTSEC-2019-0031

**Comment by kennytm** [comment]
We are using `spin::RwLock` to fix #121, so `conquer-once` is out of question.

And perhaps we should replace `spin` by `parking_lot` anyway, if the benchmark approves.

**Comment by bbigras** [comment]
Could we get a release with this fix to make `cargo audit` stop complaining?

**Comment by mxinden** [comment]
@breeswish seems like you have done all the releasing in the past. Could you either do the release or quickly document the release process? In the latter case I am happy to do the releasing in the future. I just want to make sure I am aware of all caveats.

As far as I can tell we do the following, right?

1. Update the Changelog via a pull request.

2. Push a git tag on the changelog change commit.

3. Create a release in Github.

4. Release the version to crates.io.

**Comment by lucab** [comment]
On other projects under the @coreos organization we have a workflow based on `cargo-release` plus a checklist. It goes like this (example from `coreos/zincati`):
 * release metadata in Cargo.toml: 
 * a bug template and a quick link to it: https://github.com/coreos/zincati/blob/master/docs/contributing.md#release-process
 * a list of steps to follow: https://github.com/coreos/zincati/issues/318
 * a release PR with usual review-approval rules: https://github.com/coreos/zincati/pull/320
 * tagging and publishing

Caveats:
 * we don't maintain a changelog file (but release steps can be tweaked to cover this)
 * the release PR should be merged **without rebasing** in order to maintain proper tag<->commit relationship

**Comment by mxinden** [comment]
@lucab I am fine with both my rather simple suggestion as well as your advanced suggestion, leaning towards the latter. Would you be willing to prepare the issue templates and do the first release? I am happy to take over from there on.

> we don't maintain a changelog file (but release steps can be tweaked to cover this)

I would suggest each pull request alters the `CHANGELOG` accordingly. During the release process we can then follow the suggestion of `cargo-release`, right?

https://github.com/sunng87/cargo-release/blob/f7b595f7d5cf4e1235c3f14b518351cc7f00a187/docs/faq.md#maintaining-changelog

> the release PR should be merged without rebasing in order to maintain proper tag<->commit relationship

I am guessing that even though the `master` branch is _protected_ one can still merge locally and push to `master`. That should be enough no?
