### ISSUE TITLE
Documentation on combining metrics from multiple processes

### ISSUE THREAD

**Issue by cswinter** [tikv/rust-prometheus#332]
I accidentally noticed that when you run separate Rust processes logging metrics with this crate, both of the processes seem to export all the metrics from either process. This is really useful! (Though it seems like it could also lead to metric duplication if you are unaware.) Is there any documentation on how this is implemented and under what circumstances it can be expected to work? I haven't managed to find anything so far.

**Comment by lucab** [comment]
Thanks for the report! I'm having a bit of hard time trying to understand what you are describing though.

In general, an instrumented process usually gathers and exports whatever metrics collectors are attached to the default registry. All the macros in this crate internally refer to such default default registry, so that the implicit flow makes it easy for applications to just use this singleton registry.
However, multiple processes usually do not share metrics and registry.

Can you maybe provide a small code snippet and metrics output to better highlight your doubts/questions? On which platform are you running? When you say "either process", are you perhaps instead referring to multiple application threads running within a single top-level process (i.e. still sharing some memory space)?

**Comment by cswinter** [comment]
Oh OK, I must have just confused myself then and everything was actually running inside the same process.

On that note, if I did want to do something like this is there a good solution?
Specifically, say I have multiple services running on the same node, possible inside different processes, and I want to service Prometheus scrape requests for all of these from a single known port.
Ideally, this would also work with different Prometheus clients, e.g. the Python one.
It looks like running single pushgateway on each node might make this possible, though I've not looked at that too closely yet.
Another solution might be to run a single Rust server that services scrape requests by first scraping any number of locally known services and then concatenating the results.
Do you have any thoughts on whether either of those would be a good approach?

**Comment by lucab** [comment]
@cswinter this is a general Prometheus question which I think can be better answered in usual Prometheus forums/MLs.
I can imagine a few approaches to this (including stacking multiple layers of Prometheus instances or using something like https://github.com/weaveworks/prom-aggregation-gateway), but I'm honestly not too knowledgeable on that topic.

**Comment by mxinden** [comment]
Closing here. @cswinter feel free to open up another issue in case you have further questions.
